DIAR 2117: initialise data radar
govuk-one-login/docs-common-infra pull request #7
Opened 2024-11-13 15:15 UTC by GDS-JimOC

2024-11-25 09:57 UTC, TobySaundersGDS reviewed
Hi - could we get some more detail on what this is? If this terraform has been run in already we should get it merged into main

2024-12-04 09:46 UTC, beca-galliano commented
This has been open for a while, converting to draft for now (angry seal is angry)

2025-01-06 12:59 UTC, GDS-Dominic requested changes

2025-01-06 12:59 UTC, GDS-Dominic commented on cloudformation/dns/template.yaml
> +      Name: data-radar.account.gov.uk
I think this should have an .internal in too 
```suggestion
      Name: data-radar.internal.account.gov.uk
```

2025-01-06 12:59 UTC, GDS-Dominic commented on terraform/deployments/di-documentation/pipeline-deploy/stacks.tf
> +
Missing the data-radar-ecr

2025-01-06 12:59 UTC, GDS-Dominic commented on terraform/deployments/di-documentation/pipeline-deploy/stacks.tf
> +    System             = "DI Documentation"
Is this a duplicate?

2025-01-06 17:10 UTC, GDS-JimOC commented on terraform/deployments/di-documentation/pipeline-deploy/stacks.tf
> +    System             = "DI Documentation"
mimicking what we have for event catalogue and data-exchange catalogue

2025-01-07 15:39 UTC, GDS-Dominic commented
@TobySaundersGDS  This is for the final different asset / site that Data Architecture is responsible for. Please could you review and apply the terraform please?

2025-01-07 15:39 UTC, GDS-Dominic approved these changes

2025-01-24 15:22 UTC, TobySaundersGDS approved these changes
Nice - I'll get this run in now

2025-01-24 15:22 UTC, merged